const os = require("os");
console.log("Platform: " + os.platform());
console.log("Architecture: " + os.arch());
console.log("total memory: " + os.totalmem());
console.log("total free Memory: " + os.freemem());
console.log("total uptime: " + os.uptime());
console.log("type of the operating system: " + os.type());
console.log("Release date of the Operating system: " + os.release());
console.log("host-name: " + os.hostname());
console.log("Network Interfereces: " + os.networkInterfaces());
